#!/bin/sh

script=$0
if [ -h $script ]; then
    script=`readlink $script`
fi
dir=`dirname $script`

if [ "" = "$HANNIBAL_HTTP_PORT" ]; then
    HANNIBAL_HTTP_PORT="9000"
    echo "starting Hannibal on Port 9000 (may be altered by assigning another port-number to HANNIBAL_HTTP_PORT)"
else
    echo "starting Hannibal on Port $HANNIBAL_HTTP_PORT (as defined by HANNIBAL_HTTP_PORT)"
fi

$dir/activator "start -DapplyEvolutions.default=true $HANNIBAL_HTTP_PORT"
